iris:
  DisablePathCorrection: false
  EnablePathEscape: false
  FireMethodNotAllowed: true
  DisableBodyConsumptionOnUnmarshal: true
  TimeFormat: 2006-01-02 15:04:05
  Charset: UTF-8
app:
  timezone: Asia/Shanghai
  debug: true
  bindAddress: 127.0.0.1
  port: 8888
mysql:
  host: 127.0.0.1
  port: 3306
  database: bis
  user: root

  password: root
  charset: utf8
  sqlLog: true
  maxIdleConns: 10 #Maximum number of connections when idle
  maxOpenConns: 100 #Maximum connections
  maxConnLifeTime: 60
log:
  level: debug